POST http://localhost:2222/api/meetings/0
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "room_id": 2,
  "user_login": "admin",
  "name_meeting": "Митинг",
  "start_time": 0,
  "end_time": 1
}

###
GET http://localhost:2222/api/meetings


###
GET http://localhost:2222/api/meetings/2


###
POST http://localhost:2222/api/meetings/add/result/9
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "result": "Что-то случилось"
}
###
GET http://localhost:2222/api/meetings/room/2


###

